const productos = [
    {
        id:1,
        nombre: 'Shampoo',
        valor: 900,
        detalle: 'shampoo solido de 100g',
        stock: 80,
        categoria: 'higiene',
        retornable: false,
    }, 
    {
        id:2,
        nombre: 'Acondicionador',
        valor: 900,
        detalle: 'acondicionador solido de 75g',
        stock: 0,
        categoria: 'higiene',
        retornable: false,
    },
    {
        id:3,
        nombre: 'Crema de día',
        valor: 1400,
        detalle: 'crema de calendula y manzanilla, envase retornable',
        stock: 25,
        categoria: 'cuidado de la piel',
        retornable: true,
    },
    {
        id:4,
        nombre: 'Crema de noche',
        valor: 1400,
        detalle: 'crema de lavanda y flor de hibisco, envase retornable',
        stock: 25,
        categoria: 'cuidado de la piel',
        retornable: true,
    },
    {
        id:5,
        nombre: 'Crema medicinal',
        valor: 1500,
        detalle: 'crema de cannabis y jarilla, envase retornable',
        stock: 19,
        categoria: 'cuidado de la piel',
        retornable: true,
    },
    {
        id:6,
        nombre: 'Repelente',
        valor: 1700,
        detalle: 'Repelente natural para mosquitos',
        stock: 0,
        categoria:'higiene',
        retornable: true,
    },
    {
        id:7,
        nombre: 'Balsamo labial',
        valor: 500,
        detalle: 'Balsamo labial de manteca de cacao, envase retornable',
        stock: 15,
        categoria:'cuidado de la piel',
        retornable: true,
    },
    {
        id:8,
        nombre: 'Shampoo para barba',
        valor: 900,
        detalle: 'shampoo solido para barba de 70g',
        stock: 50,
        categoria: 'higiene',
        retornable: false,
    },
]
